version: '3.8'

services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://myuser:200899@147.93.31.224:5432/ipm
    ports:
      - "8000:8000"
    command: >
      sh -c "/entrypoint.sh"