services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://myuser:200899@147.93.31.224:5432/ipm_new
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./secret_file.json:/app/src/app/utils/firebase/secret_files.json
