from typing import List, Dict

class LocationService:
    # Comprehensive dictionary of Indian states and their major cities
    # _INDIA_STATES_CITIES: Dict[str, List[str]] = {
    #     "andhra pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati"],
    #     "arunachal pradesh": ["Itanagar", "Tawang", "Pasighat", "Ziro"],
    #     "assam": ["Guwahati", "Dibrugarh", "Silchar", "Tezpur"],
    #     "bihar": ["Patna", "Gaya", "Darbhanga", "Bhagalpur"],
    #     "chhattisgarh": ["Raipur", "Bilaspur", "Korba", "Durg", "Raigarh"],
    #     "goa": ["Panaji", "Vasco da Gama", "Margao", "Mapusa", "Ponda"],
    #     "gujarat": ["Ahmedabad", "Vadodara", "Surat", "Rajkot", "Gandhinagar", "Bhavnagar", "Jamnagar", "Junagadh"],
    #     "haryana": ["Faridabad", "Gurugram", "Sonipat", "Panipat", "Ambala"],
    #     "himachal pradesh": ["Shimla", "Dharamshala", "Mandi", "Solan", "Chamba"],
    #     "jharkhand": ["Ranchi", "Jamshedpur", "Bokaro", "Dhanbad", "Deoghar", "Hazaribagh"],
    #     "karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum", "Gulbarga", "Dharwad", "Shimoga"],
    #     "kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad"],
    #     "madhya pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar"],
    #     "maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur"],
    #     "manipur": ["Imphal", "Bishnupur", "Ukhrul", "Tamenglong"],
    #     "meghalaya": ["Shillong", "Cherrapunji", "Tura", "Jowai"],
    #     "mizoram": ["Aizawl", "Lunglei", "Serchhip", "Champhai"],
    #     "nagaland": ["Kohima", "Mokokchung", "Tuensang", "Zunheboto"],
    #     "odisha": ["Bhubaneswar", "Rourkela", "Cuttack", "Brahmapur", "Sambalpur", "Puri"],
    #     "punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala"],
    #     "rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner", "Bharatpur", "Sikar"],
    #     "sikkim": ["Gangtok", "Namchi", "Mangan"],
    #     "tamil nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli", "Tiruppur", "Vellore"],
    #     "telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam", "Khammam"],
    #     "tripura": ["Agartala", "Amarpur", "Kumarghat"],
    #     "uttar pradesh": ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut", "Allahabad", "Ghaziabad", "Noida"],
    #     "uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Rishikesh"],
    #     "west bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman", "Malda"],
    # }

    _INDIA_STATES_CITIES = {
        # States
        "andhra pradesh": [
            "Amaravati",
            "Visakhapatnam",
            "Vijayawada",
            "Guntur",
            "Tirupati",
            "Vijayawada",
        ],
        "arunachal pradesh": ["Itanagar", "Tawang", "Pasighat", "Ziro"],
        "assam": ["Dispur", "Guwahati", "Dibrugarh", "Silchar", "Tezpur"],
        "bihar": ["Patna", "Gaya", "Darbhanga", "Bhagalpur"],
        "chhattisgarh": ["Raipur", "Bilaspur", "Korba", "Durg", "Raigarh"],
        "goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
        "gujarat": [
            "Gandhinagar",
            "Ahmedabad",
            "Vadodara",
            "Surat",
            "Rajkot",
            "Bhavnagar",
            "Jamnagar",
            "Junagadh",
        ],
        "haryana": [
            "Chandigarh",
            "Faridabad",
            "Gurugram",
            "Sonipat",
            "Panipat",
            "Ambala",
        ],
        "himachal pradesh": ["Shimla", "Dharamshala", "Mandi", "Solan", "Chamba"],
        "jharkhand": [
            "Ranchi",
            "Jamshedpur",
            "Bokaro",
            "Dhanbad",
            "Deoghar",
            "Hazaribagh",
        ],
        "karnataka": [
            "Bengaluru",
            "Mysore",
            "Hubli",
            "Mangalore",
            "Belgaum",
            "Gulbarga",
            "Dharwad",
            "Shimoga",
        ],
        "kerala": [
            "Thiruvananthapuram",
            "Kochi",
            "Kozhikode",
            "Thrissur",
            "Kollam",
            "Palakkad",
        ],
        "madhya pradesh": [
            "Bhopal",
            "Indore",
            "Gwalior",
            "Jabalpur",
            "Ujjain",
            "Sagar",
        ],
        "maharashtra": [
            "Mumbai",
            "Pune",
            "Nagpur",
            "Thane",
            "Nashik",
            "Aurangabad",
            "Solapur",
            "Kolhapur",
        ],
        "manipur": ["Imphal", "Bishnupur", "Ukhrul", "Tamenglong"],
        "meghalaya": ["Shillong", "Cherrapunji", "Tura", "Jowai"],
        "mizoram": ["Aizawl", "Lunglei", "Serchhip", "Champhai"],
        "nagaland": ["Kohima", "Mokokchung", "Tuensang", "Zunheboto"],
        "odisha": [
            "Bhubaneswar",
            "Cuttack",
            "Rourkela",
            "Brahmapur",
            "Sambalpur",
            "Puri",
        ],
        "punjab": ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala"],
        "rajasthan": [
            "Jaipur",
            "Jodhpur",
            "Udaipur",
            "Kota",
            "Ajmer",
            "Bikaner",
            "Bharatpur",
            "Sikar",
        ],
        "sikkim": ["Gangtok", "Namchi", "Mangan"],
        "tamil nadu": [
            "Chennai",
            "Coimbatore",
            "Madurai",
            "Salem",
            "Tiruchirappalli",
            "Tiruppur",
            "Vellore",
        ],
        "telangana": [
            "Hyderabad",
            "Warangal",
            "Nizamabad",
            "Karimnagar",
            "Ramagundam",
            "Khammam",
        ],
        "tripura": ["Agartala", "Amarpur", "Kumarghat"],
        "uttar pradesh": [
            "Lucknow",
            "Kanpur",
            "Varanasi",
            "Agra",
            "Meerut",
            "Allahabad",
            "Ghaziabad",
            "Noida",
        ],
        "uttarakhand": ["Dehradun", "Nainital", "Haridwar", "Roorkee", "Rishikesh"],
        "west bengal": [
            "Kolkata",
            "Howrah",
            "Durgapur",
            "Asansol",
            "Siliguri",
            "Bardhaman",
            "Malda",
        ],
        # Union Territories
        "andaman and nicobar islands": ["Port Blair"],
        "chandigarh": ["Chandigarh"],
        "dadra and nagar haveli and daman and diu": ["Daman", "Silvassa"],
        "delhi": ["New Delhi", "Delhi"],
        "jammu and kashmir": ["Srinagar", "Jammu"],
        "ladakh": ["Leh", "Kargil"],
        "lakshadweep": ["Kavaratti"],
        "puducherry": ["Puducherry", "Pondicherry"],
        # Major NCR satellite cities
        "_ncr": [
            "Noida",
            "Greater Noida",
            "Gurugram",
            "Faridabad",
            "Ghaziabad",
            "Meerut",
            "Alwar",
            "Baghpat",
            "Panipat",
            "Karnal",
        ],
    }
